### ISSUE TITLE
Filter linkedin in the manifest.json

### ISSUE THREAD

**Issue by raszi** [dinkom/linkedin_notification_remover#1]
There is a [way to filter](http://stackoverflow.com/questions/10396634/chrome-extension-run-for-a-specific-page) for a specific site in the manifest.json, then you won't need to do that in the content script.

**Comment by dinkom** [comment]
Oh, cool, didn't know that! :) Chrome extensions are not usually what I
code, but I got so annoyed by that feature from LinkedIn, I had to code
something.

Thanks and best regards,
Dinko M.
